// Dados integrados dos 3 arquivos CSV
const rawData = [
    // ============================================
    // ANÁLISE GERAL (arquivo original)
    // ============================================
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CAPA_DOCUMENTOS_JUDICIAIS",
        visualizaDocumentos: "PARCIALMENTE",
        peticiona: "NÃO",
        comentarios: "Só visualiza documentos feitos pelas unidades judiciais",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "SIM",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Não é possível dar permissão expressa para sigilo 0 diretamente. No entanto, ao elevar o sigilo, conceder permissão expressa para aquele sigilo e depois retornar o nível de sigilo para 0, o sistema permite adequar a permissão anteriormente dada ao sigilo atual do processo. Assim, é possível contornar o sistema e conceder permissão expressa para sigilo 0",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "PARCIALMENTE",
        tipoAcesso: "PARCIAL_SEM_SIGILO_1",
        visualizaDocumentos: "PARCIALMENTE",
        peticiona: "NÃO",
        comentarios: "Concedida permissão para sigilo 0, ele somente não verá documentos sob sigilo 1 e acima",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "SIM",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "A permissão expressa concede acesso a todos os documentos dos autos de sigilo inferior ao permitido",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "NÃO",
        rito: "NÃO",
        localidadeRito: "Nenhum",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CAPA_DOCUMENTOS_JUDICIAIS",
        visualizaDocumentos: "PARCIALMENTE",
        peticiona: "NÃO",
        comentarios: "Só visualiza documentos feitos pelas unidades judiciais",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "PARCIALMENTE",
        mpIntimado: "N/A",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "O analista consegue visualizar o documento mesmo não estando na localidade de atuação em que está cadastrado, pois o procurador vinculado está devidamente cadastrado na localidade.",
        processo: "4000007-02.2025.8.26.0016",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "O analista consegue visualizar o documento mesmo não estando na localidade de atuação em que está cadastrado, pois o procurador vinculado está devidamente cadastrado na localidade.",
        processo: "4000171-12.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "Nesse caso só foi aumentado o nivel de sigilo e o analista continua conseguindo visualizar.",
        processo: "4000171-12.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "PARCIALMENTE",
        mpIntimado: "N/A",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.",
        processo: "4000164-20.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "PARCIALMENTE",
        mpIntimado: "N/A",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.",
        processo: "4000269-94.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },

    // ============================================
    // COM INTIMAÇÃO DO MP
    // ============================================
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado ao procurador, mesma comarca e rito",
        processo: "4000432-28.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, mesma comarca e rito",
        processo: "4000432-28.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "PARCIAL_LOCALIDADE",
        rito: "SIM",
        localidadeRito: "Apenas Loc.",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, mesma localidade apenas (sem rito compatível)",
        processo: "4000432-28.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, documento com sigilo 1",
        processo: "4000433-13.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado, documento com sigilo 1",
        processo: "4000433-13.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, documento com sigilo 1",
        processo: "4000433-13.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado, documento com sigilo 2",
        processo: "4005403-38.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, documento com sigilo 2",
        processo: "4005403-38.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, localidade diferente",
        processo: "4005403-38.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, processo com sigilo 1",
        processo: "4005405-08.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, processo sigilo 1, localidade diferente",
        processo: "4005405-08.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado, processo sigilo 1",
        processo: "4005405-08.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 1,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, processo e documento sigilo 1",
        processo: "4000434-95.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 2,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, processo e documento sigilo 2",
        processo: "4005408-60.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "PARCIAL_RITO",
        rito: "SIM",
        localidadeRito: "Apenas Rito",
        sigiloProcesso: 2,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, mesmo rito apenas",
        processo: "4005408-60.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 3,
        sigiloDocumento: 3,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, sigilo 3 - necessita permissão expressa",
        processo: "4005409-45.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        localidadeRito: "Ambos",
        sigiloProcesso: 4,
        sigiloDocumento: 4,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, sigilo 4 - processo sigiloso",
        processo: "4000436-65.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "N/A",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 5,
        sigiloDocumento: 5,
        permissaoExpressa: "N/A",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Sigilo 5 com acesso somente para o Juíz",
        processo: "4005399-98.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },

    // ============================================
    // SEM INTIMAÇÃO DO MP (mas com/sem Vista ao MP)
    // ============================================
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CAPA_BASICA",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Sem intimação, sem Vista - somente informações básicas da capa, não consegue visualizar os documentos no evento",
        processo: "4000425-36.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_DOCUMENTOS",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Sem intimação, COM Vista - acesso à capa e documentos (não peticiona)",
        processo: "4000425-36.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CAPA_BASICA",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Sem intimação, sem Vista, documento sigilo 1 - somente capa básica",
        processo: "4000427-06.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_DOCUMENTOS",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Sem intimação, COM Vista, documento sigilo 1 - acesso à capa e documentos",
        processo: "4000427-06.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CABECALHO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 1, sem Vista - somente cabeçalho da capa com nome das partes, não consegue visualizar os eventos",
        processo: "4000426-21.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CABECALHO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 1, COM Vista - somente cabeçalho da capa, Vista não ajuda com sigilo 1",
        processo: "4000426-21.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_DOCUMENTOS",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 2, COM Vista - acesso à capa e documentos (Vista ao MP funciona!)",
        processo: "4000429-73.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 2, sem Vista - nenhum acesso",
        processo: "4000429-73.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 3,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 3, COM Vista - nenhum acesso (sigilo 3+ bloqueia mesmo com Vista)",
        processo: "4000430-58.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 3,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_EVENTOS_SEM_DOCS",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 0, documentos sigilo 3, COM Vista - acesso à capa e eventos, mas não aos documentos",
        processo: "4000290-49.2025.8.26.0008",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 4,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_EVENTOS_SEM_DOCS",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 0, documentos sigilo 4, COM Vista - acesso à capa e eventos, mas não aos documentos",
        processo: "4005398-16.2025.8.26.0960",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 4,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 4, sem Vista - nenhum acesso",
        processo: "4000291-34.2025.8.26.0008",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 4,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 4, COM Vista - nenhum acesso",
        processo: "4000291-34.2025.8.26.0008",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        localidadeRito: "N/A",
        sigiloProcesso: 5,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 5 - nenhum acesso (exclusivo do Juiz)",
        processo: "4005399-98.2025.8.26.0960",
        fonte: "SEM_INTIMACAO_MP"
    }
];

// Estatísticas atualizadas
const stats = {
    totalCenarios: rawData.length,
    acessoTotal: rawData.filter(r => r.visualizaDocumentos === 'SIM').length,
    acessoParcial: rawData.filter(r => r.visualizaDocumentos === 'PARCIALMENTE').length,
    acessoNegado: rawData.filter(r => r.visualizaDocumentos === 'NÃO').length,
    podePeticionar: rawData.filter(r => r.peticiona === 'SIM').length,
    comIntimacao: rawData.filter(r => r.mpIntimado === 'SIM').length,
    semIntimacao: rawData.filter(r => r.mpIntimado === 'NÃO').length,
    comVista: rawData.filter(r => r.vistaMP === 'SIM').length
};

// Cenários estruturados atualizados serão mantidos conforme relatório original
const scenarios = [
    {
        id: "1",
        titulo: "Intimação do MP vs Vista ao MP",
        descricao: "Intimação do MP é uma vinculação forte que, combinada com vinculação do procurador, permite peticionamento. Vista ao MP é vinculação parcial que concede acesso mas não permite peticionar.",
        relevancia: "CRÍTICA"
    },
    {
        id: "2",
        titulo: "Vista ao MP com Sigilo 2",
        descricao: "Descoberta importante: processos com sigilo 2 SEM intimação mas COM Vista ao MP concedem acesso total à capa e documentos. A Vista ao MP é mais forte do que previsto inicialmente.",
        relevancia: "ALTA"
    },
    {
        id: "3",
        titulo: "Sigilos 3, 4 e 5",
        descricao: "Sigilo 3 requer permissão expressa. Sigilo 4 bloqueia acesso mesmo com intimação e vinculação. Sigilo 5 é exclusivo do Juiz.",
        relevancia: "CRÍTICA"
    },
    {
        id: "4",
        titulo: "Capacidade de Peticionamento",
        descricao: "Para peticionar, o analista precisa: MP intimado + Analista vinculado ao procurador + Mesma comarca E rito + Sigilo 0-2. Falta de qualquer um desses fatores impede peticionamento.",
        relevancia: "ALTA"
    },
    {
        id: "5",
        titulo: "Granularidade de Acesso",
        descricao: "Existem 7 níveis de acesso: Total, Capa+Documentos, Capa+Eventos sem Docs, Apenas Capa Básica, Apenas Cabeçalho, Apenas Documentos Judiciais, Negado.",
        relevancia: "MÉDIA"
    }
];