// Dados integrados dos 3 arquivos CSV
const rawData = [
    // ============================================
    // ANÁLISE GERAL (arquivo original)
    // ============================================
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CAPA_DOCUMENTOS_JUDICIAIS",
        visualizaDocumentos: "PARCIALMENTE",
        peticiona: "NÃO",
        comentarios: "Só visualiza documentos feitos pelas unidades judiciais",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "NÃO",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.",
        processo: "",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "O analista consegue visualizar o documento mesmo não estando na localidade de atuação em que está cadastrado, pois o procurador vinculado está devidamente cadastrado na localidade.",
        processo: "4000007-02.2025.8.26.0016",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "O analista consegue visualizar o documento mesmo não estando na localidade de atuação em que está cadastrado, pois o procurador vinculado está devidamente cadastrado na localidade.",
        processo: "4000171-12.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "N/A",
        vistaMP: "N/A",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "Nesse caso só foi aumentado o nivel de sigilo e o analista continua conseguindo visualizar.",
        processo: "4000171-12.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.",
        processo: "4000164-20.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "N/A",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.",
        processo: "4000269-94.2025.8.26.0001",
        fonte: "ANALISE_GERAL"
    },

    // ============================================
    // COM INTIMAÇÃO DO MP
    // ============================================
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado ao procurador, mesma comarca e rito",
        processo: "4000432-28.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, mesma comarca e rito",
        processo: "4000432-28.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "PARCIAL_LOCALIDADE",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, mesma localidade apenas (sem rito compatível)",
        processo: "4000432-28.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, documento com sigilo 1",
        processo: "4000433-13.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado, documento com sigilo 1",
        processo: "4000433-13.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado, documento com sigilo 2",
        processo: "4005403-38.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, documento com sigilo 2",
        processo: "4005403-38.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 0,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, localidade diferente",
        processo: "4005403-38.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, processo com sigilo 1",
        processo: "4005405-08.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "NÃO",
        rito: "SIM",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, processo sigilo 1, localidade diferente",
        processo: "4005405-08.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista não vinculado, processo sigilo 1",
        processo: "4005405-08.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 1,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, processo e documento sigilo 1",
        processo: "4000434-95.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 2,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "SIM",
        comentarios: "MP intimado, analista vinculado, processo e documento sigilo 2",
        processo: "4005408-60.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "PARCIAL_RITO",
        rito: "SIM",
        sigiloProcesso: 2,
        sigiloDocumento: 2,
        permissaoExpressa: "NÃO",
        tipoAcesso: "TOTAL",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, mesmo rito apenas",
        processo: "4005408-60.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 3,
        sigiloDocumento: 3,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, sigilo 3 - necessita permissão expressa",
        processo: "4005409-45.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "SIM",
        mpIntimado: "SIM",
        vistaMP: "SIM",
        localidade: "SIM",
        rito: "SIM",
        sigiloProcesso: 4,
        sigiloDocumento: 4,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "MP intimado, analista vinculado, sigilo 4 - processo sigiloso",
        processo: "4000436-65.2025.8.26.0081",
        fonte: "COM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 5,
        sigiloDocumento: 5,
        permissaoExpressa: "N/A",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Sigilo 5 com acesso somente para o Juíz",
        processo: "4005399-98.2025.8.26.0960",
        fonte: "COM_INTIMACAO_MP"
    },

    // ============================================
    // SEM INTIMAÇÃO DO MP (mas com/sem Vista ao MP)
    // ============================================
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_DOCUMENTOS",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Sem intimação, COM Vista - acesso à capa e documentos (não peticiona)",
        processo: "4000425-36.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CAPA_BASICA",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Sem intimação, sem Vista, documento sigilo 1 - somente capa básica",
        processo: "4000427-06.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 1,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_DOCUMENTOS",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Sem intimação, COM Vista, documento sigilo 1 - acesso à capa e documentos",
        processo: "4000427-06.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CABECALHO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 1, sem Vista - somente cabeçalho da capa com nome das partes, não consegue visualizar os eventos",
        processo: "4000426-21.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 1,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "APENAS_CABECALHO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 1, COM Vista - somente cabeçalho da capa, Vista não ajuda com sigilo 1",
        processo: "4000426-21.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_DOCUMENTOS",
        visualizaDocumentos: "SIM",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 2, COM Vista - acesso à capa e documentos (Vista ao MP funciona!)",
        processo: "4000429-73.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 2,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 2, sem Vista - nenhum acesso",
        processo: "4000429-73.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 3,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 3, COM Vista - nenhum acesso (sigilo 3+ bloqueia mesmo com Vista)",
        processo: "4000430-58.2025.8.26.0081",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 3,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_EVENTOS_SEM_DOCS",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 0, documentos sigilo 3, COM Vista - acesso à capa e eventos, mas não aos documentos",
        processo: "4000290-49.2025.8.26.0008",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 0,
        sigiloDocumento: 4,
        permissaoExpressa: "NÃO",
        tipoAcesso: "CAPA_E_EVENTOS_SEM_DOCS",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 0, documentos sigilo 4, COM Vista - acesso à capa e eventos, mas não aos documentos",
        processo: "4005398-16.2025.8.26.0960",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 4,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 4, sem Vista - nenhum acesso",
        processo: "4000291-34.2025.8.26.0008",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "SIM",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 4,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 4, COM Vista - nenhum acesso",
        processo: "4000291-34.2025.8.26.0008",
        fonte: "SEM_INTIMACAO_MP"
    },
    {
        perfil: "Analista Procuradoria",
        procuradorVinculado: "NÃO",
        mpIntimado: "NÃO",
        vistaMP: "NÃO",
        localidade: "N/A",
        rito: "N/A",
        sigiloProcesso: 5,
        sigiloDocumento: 0,
        permissaoExpressa: "NÃO",
        tipoAcesso: "NEGADO",
        visualizaDocumentos: "NÃO",
        peticiona: "NÃO",
        comentarios: "Processo sigilo 5 - nenhum acesso (exclusivo do Juiz)",
        processo: "4005399-98.2025.8.26.0960",
        fonte: "SEM_INTIMACAO_MP"
    }
];

// Estatísticas atualizadas
const stats = {
    totalCenarios: rawData.length,
    acessoTotal: rawData.filter(r => r.visualizaDocumentos === 'SIM').length,
    acessoParcial: rawData.filter(r => r.visualizaDocumentos === 'PARCIALMENTE').length,
    acessoNegado: rawData.filter(r => r.visualizaDocumentos === 'NÃO').length,
    podePeticionar: rawData.filter(r => r.peticiona === 'SIM').length,
    comIntimacao: rawData.filter(r => r.mpIntimado === 'SIM').length,
    semIntimacao: rawData.filter(r => r.mpIntimado === 'NÃO').length,
    comVista: rawData.filter(r => r.vistaMP === 'SIM').length
};

// Cenários estruturados baseados nos dados da matriz de acesso
const scenarios = [
    {
        id: "1",
        titulo: "Cenário Ideal: Intimação + Vinculação + Localidade/Rito",
        sigiloProcesso: 0,
        sigiloDocumentos: 0,
        procurador: true,
        entidade: true,
        resultado: "TOTAL",
        anomalia: false,
        descricao: "MP intimado, analista vinculado ao procurador, mesma comarca e rito. Cenário ideal que permite acesso total com capacidade de peticionamento até sigilo 2.",
        relevancia: "CRÍTICA"
    },
    {
        id: "2",
        titulo: "Descoberta: Vista ao MP + Sigilo 2 (Mais Forte que Previsto)",
        sigiloProcesso: 2,
        sigiloDocumentos: 0,
        procurador: false,
        entidade: false,
        resultado: "PARCIAL",
        anomalia: true,
        descricao: "Processo sigilo 2 SEM intimação mas COM Vista ao MP concede acesso total aos documentos. Vista ao MP é mais forte do que previsto inicialmente - não permite peticionamento mas garante visualização.",
        relevancia: "ALTA"
    },
    {
        id: "3",
        titulo: "Anomalia: Sigilo 1 + Vista ao MP (Comportamento Inconsistente)",
        sigiloProcesso: 1,
        sigiloDocumentos: 0,
        procurador: false,
        entidade: false,
        resultado: "NEGADO",
        anomalia: true,
        descricao: "Vista ao MP não funciona para sigilo 1, apenas cabeçalho disponível. Comportamento inconsistente: funciona para sigilo 0 e 2, mas não para 1.",
        relevancia: "ALTA"
    },
    {
        id: "4",
        titulo: "Vulnerabilidade: Contorno de Permissão Expressa Sigilo 0",
        sigiloProcesso: 0,
        sigiloDocumentos: 0,
        procurador: false,
        entidade: false,
        resultado: "TOTAL",
        anomalia: true,
        descricao: "Sistema não permite permissão expressa direta para sigilo 0, mas é possível contornar: elevar sigilo → conceder permissão → retornar para 0. Sistema mantém permissão anterior.",
        relevancia: "CRÍTICA"
    },
    {
        id: "5",
        titulo: "Localidade/Rito: Impacta Peticionamento, Não Visualização",
        sigiloProcesso: 0,
        sigiloDocumentos: 2,
        procurador: true,
        entidade: true,
        resultado: "PARCIAL",
        anomalia: false,
        descricao: "Analista vinculado com localidade diferente: tem acesso total aos documentos mas NÃO pode peticionar. Localidade/rito só é relevante para peticionamento.",
        relevancia: "MÉDIA"
    },
    {
        id: "6",
        titulo: "Sigilo 3: Requer Permissão Expressa",
        sigiloProcesso: 3,
        sigiloDocumentos: 3,
        procurador: true,
        entidade: true,
        resultado: "NEGADO",
        anomalia: false,
        descricao: "Mesmo com intimação + vinculação + localidade compatível, sigilo 3 bloqueia acesso. Necessita permissão expressa específica para este nível.",
        relevancia: "ALTA"
    },
    {
        id: "7",
        titulo: "Sigilo 4: Requer Permissão Expressa",
        sigiloProcesso: 4,
        sigiloDocumentos: 4,
        procurador: true,
        entidade: true,
        resultado: "NEGADO",
        anomalia: false,
        descricao: "Sigilo 4 bloqueia acesso mesmo com intimação + vinculação + localidade. Com permissão expressa específica, o analista consegue consultar e peticionar normalmente.",
        relevancia: "CRÍTICA"
    },
    {
        id: "8",
        titulo: "Sigilo 5: Requer Permissão Expressa",
        sigiloProcesso: 5,
        sigiloDocumentos: 5,
        procurador: false,
        entidade: false,
        resultado: "NEGADO",
        anomalia: false,
        descricao: "Sigilo 5 é o nível mais restritivo. Sem permissão expressa, o acesso é exclusivo do Juiz. Com permissão expressa específica, o analista consegue consultar e peticionar.",
        relevancia: "CRÍTICA"
    },
    {
        id: "9",
        titulo: "Granularidade: Documentos Sigilo 3+ com Vista ao MP",
        sigiloProcesso: 0,
        sigiloDocumentos: 3,
        procurador: false,
        entidade: false,
        resultado: "PARCIAL",
        anomalia: false,
        descricao: "Processo público com documentos sigilo 3+ e Vista ao MP: acesso à capa e eventos, mas NÃO aos documentos. Demonstra granularidade do controle de acesso.",
        relevancia: "MÉDIA"
    },
    {
        id: "10",
        titulo: "Sem Intimação + Sem Vista: Mínimo Acesso",
        sigiloProcesso: 0,
        sigiloDocumentos: 0,
        procurador: false,
        entidade: false,
        resultado: "NEGADO",
        anomalia: false,
        descricao: "Processo público sem intimação nem Vista ao MP: apenas informações básicas da capa. Não consegue visualizar documentos nem eventos.",
        relevancia: "BAIXA"
    }
];