-- ===========================
-- POPULAR TABELA MATRIZ DE ACESSO
-- ===========================

-- Limpar dados existentes (opcional)
-- TRUNCATE TABLE matriz_acesso RESTART IDENTITY CASCADE;

-- Inserir dados
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 0, 0, 'APENAS_CAPA_DOCUMENTOS_JUDICIAIS', 'Só visualiza documentos feitos pelas unidades judiciais', '', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 0, 1, 'NEGADO', '', '', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 1, 'TOTAL', 'O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.', '', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('N/A', 'SIM', 0, 0, 'TOTAL', 'O analista consegue visualizar o documento mesmo não estando na localidade de atuação em que está cadastrado, pois o procurador vinculado está devidamente cadastrado na localidade.', '4000007-02.2025.8.26.0016', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('N/A', 'SIM', 1, 0, 'TOTAL', 'O analista consegue visualizar o documento mesmo não estando na localidade de atuação em que está cadastrado, pois o procurador vinculado está devidamente cadastrado na localidade.', '4000171-12.2025.8.26.0001', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('N/A', 'SIM', 2, 0, 'TOTAL', 'Nesse caso só foi aumentado o nivel de sigilo e o analista continua conseguindo visualizar.', '4000171-12.2025.8.26.0001', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 2, 0, 'TOTAL', 'O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.', '4000164-20.2025.8.26.0001', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 2, 'TOTAL', 'O Processo possui Vista ao MP, mas não possui vinculação direta com o procurador.', '4000269-94.2025.8.26.0001', 'ANALISE_GERAL');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 0, 'TOTAL', 'MP intimado, analista não vinculado ao procurador, mesma comarca e rito', '4000432-28.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 0, 0, 'TOTAL', 'MP intimado, analista vinculado, mesma comarca e rito', '4000432-28.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 0, 0, 'TOTAL', 'MP intimado, analista vinculado, mesma localidade apenas (sem rito compatível)', '4000432-28.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 0, 1, 'TOTAL', 'MP intimado, analista vinculado, documento com sigilo 1', '4000433-13.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 1, 'TOTAL', 'MP intimado, analista não vinculado, documento com sigilo 1', '4000433-13.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 2, 'TOTAL', 'MP intimado, analista não vinculado, documento com sigilo 2', '4005403-38.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 0, 2, 'TOTAL', 'MP intimado, analista vinculado, documento com sigilo 2', '4005403-38.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 0, 2, 'TOTAL', 'MP intimado, analista vinculado, localidade diferente', '4005403-38.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 1, 0, 'TOTAL', 'MP intimado, analista vinculado, processo com sigilo 1', '4005405-08.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 1, 0, 'NEGADO', 'MP intimado, analista vinculado, processo sigilo 1, localidade diferente', '4005405-08.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 1, 0, 'NEGADO', 'MP intimado, analista não vinculado, processo sigilo 1', '4005405-08.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 1, 1, 'TOTAL', 'MP intimado, analista vinculado, processo e documento sigilo 1', '4000434-95.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 2, 2, 'TOTAL', 'MP intimado, analista vinculado, processo e documento sigilo 2', '4005408-60.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 2, 2, 'TOTAL', 'MP intimado, analista vinculado, mesmo rito apenas', '4005408-60.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 3, 3, 'NEGADO', 'MP intimado, analista vinculado, sigilo 3 - necessita permissão expressa', '4005409-45.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'SIM', 4, 4, 'NEGADO', 'MP intimado, analista vinculado, sigilo 4 - processo sigiloso', '4000436-65.2025.8.26.0081', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 5, 5, 'NEGADO', 'Sigilo 5 com acesso somente para o Juíz', '4005399-98.2025.8.26.0960', 'COM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 0, 'CAPA_E_DOCUMENTOS', 'Sem intimação, COM Vista - acesso à capa e documentos (não peticiona)', '4000425-36.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 0, 1, 'APENAS_CAPA_BASICA', 'Sem intimação, sem Vista, documento sigilo 1 - somente capa básica', '4000427-06.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 1, 'CAPA_E_DOCUMENTOS', 'Sem intimação, COM Vista, documento sigilo 1 - acesso à capa e documentos', '4000427-06.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 1, 0, 'APENAS_CABECALHO', 'Processo sigilo 1, sem Vista - somente cabeçalho da capa com nome das partes, não consegue visualizar os eventos', '4000426-21.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 1, 0, 'APENAS_CABECALHO', 'Processo sigilo 1, COM Vista - somente cabeçalho da capa, Vista não ajuda com sigilo 1', '4000426-21.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 2, 0, 'CAPA_E_DOCUMENTOS', 'Processo sigilo 2, COM Vista - acesso à capa e documentos (Vista ao MP funciona!)', '4000429-73.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 2, 0, 'NEGADO', 'Processo sigilo 2, sem Vista - nenhum acesso', '4000429-73.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 3, 0, 'NEGADO', 'Processo sigilo 3, COM Vista - nenhum acesso (sigilo 3+ bloqueia mesmo com Vista)', '4000430-58.2025.8.26.0081', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 3, 'CAPA_E_EVENTOS_SEM_DOCS', 'Processo sigilo 0, documentos sigilo 3, COM Vista - acesso à capa e eventos, mas não aos documentos', '4000290-49.2025.8.26.0008', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 0, 4, 'CAPA_E_EVENTOS_SEM_DOCS', 'Processo sigilo 0, documentos sigilo 4, COM Vista - acesso à capa e eventos, mas não aos documentos', '4005398-16.2025.8.26.0960', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 4, 0, 'NEGADO', 'Processo sigilo 4, sem Vista - nenhum acesso', '4000291-34.2025.8.26.0008', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('SIM', 'NÃO', 4, 0, 'NEGADO', 'Processo sigilo 4, COM Vista - nenhum acesso', '4000291-34.2025.8.26.0008', 'SEM_INTIMACAO_MP');
INSERT INTO matriz_acesso (vista_mp, procurador_vinculado, sigilo_processo, sigilo_documento, tipo_acesso, observacoes, processo, fonte) VALUES ('NÃO', 'NÃO', 5, 0, 'NEGADO', 'Processo sigilo 5 - nenhum acesso (exclusivo do Juiz)', '4005399-98.2025.8.26.0960', 'SEM_INTIMACAO_MP');

-- Total de registros inseridos: 38
